version: '3.8'

services:
  server-load-1:
    container_name: load-1
    build:
      context: ./backend1
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    networks:
      - backend-network

  server-load-2:
    container_name: load-2
    build:
      context: ./backend2
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    networks:
      - backend-network

  nginx-load-proxy:
    image: nginx:latest
    container_name: nginx-load-proxy
    ports:
      - "8888:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
